- job:
    name: 'sat-release-hammer-cli-foreman-virt-who-configure'
    project-type: pipeline
    sandbox: true
    parameters:
      - release_branch
    auth-token: ""
    dsl:
      !include-raw:
          - workflows/lib/branch_map.groovy
          - ./repos/hammer_cli_foreman_virt_who_configure_repo.groovy
          - ./source_types/sourceTypeGem.groovy
          - workflows/releasePackageWorkflow.groovy
          - workflows/lib/toolbelt.groovy
          - foreman-infra/pipelines/lib/ansible.groovy
          - foreman-infra/pipelines/lib/virtualEnv.groovy
          - workflows/lib/runPlaybook.groovy
    notifications:
      - snapper_notifications
