- job:
    disabled: false
    name: 'sat-release-hammer-cli-foreman-virt-who-configure'
    project-type: workflow
    parameters:
      - release_branch
    auth-token: ""
    dsl:
      !include-raw:
          - ./repos/hammer_cli_foreman_virt_who_configure_repo.groovy
          - ./source_types/sourceTypeGem.groovy
          - workflows/releasePackageWorkflow.groovy
          - workflows/lib/toolbelt.groovy
          - workflows/lib/runPlaybook.groovy
    notifications:
      - snapper_notifications
