sudo: false
language: python
install:
  - pip install -r requirements.txt
  - pip install lxml
script:
  - ./setup_jjb.sh
  - echo -e '[jenkins]\nurl=http://127.0.0.1:8080/' >> jenkins_jobs.ini
  - ./generate_jobs.sh
  - 'git grep -l "project-type:.*pipeline" |xargs -n1 grep -m1 "name:" |cut -d: -f2 | xargs -n1 -I@@ python foreman-infra/jenkins-lint.py --xml /tmp/jobs/@@'
