---
- hosts: compose
  become: true
  become_user: jenkins
  vars:
    compose_conf_dir: "/home/jenkins/compose_repo"
    compose_output_dir: "/home/jenkins/composes"
  tasks:
    - debug:
        msg: "Generating compose for {{ distro|upper }}{{ distro_version }}"

    - name: 'Find compose symlink'
      command: "readlink -f {{ compose_output_dir }}/latest-{{ compose_label }}-{{ distro|upper }}-{{ distro_version }}/"
      register: compose_link

    - name: 'Remove old compose'
      file:
        state: absent
        path: "{{ compose_link.stdout }}"

    - name: 'Generate compose'
      command: "pungi-koji --test --config={{ compose_conf_dir }}/pungi/satellite-6/{{ compose_version }}/{{ compose_name }}-{{ distro }}-{{ distro_version }}-{{ compose_tag }}.conf --target-dir={{ compose_output_dir }} --skip-phase=createiso --skip-phase=live_images --skip-phase=extra_files"

    - name: 'Find repos to cleanup'
      find:
        file_type: directory
        patterns: "repo-*"
        paths: "."
      register: repos

    - name: 'Cleanup repos'
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ repos.files }}"

