---
- hosts: localhost
  roles:
    - role: theforeman.foreman.content_view_version_cleanup
      vars:
        foreman_username: "{{ username }}"
        foreman_password: "{{ password }}"
        foreman_server_url: "{{ server }}"
        foreman_validate_certs: False
        foreman_organization: "{{ organization }}"
        foreman_content_view_version_cleanup_keep: 5
