---
- hosts: localhost
  tasks:
  - name: "copy activation key '{{ activation_key_name }}'"
    theforeman.foreman.activation_key:
      username: "{{ username }}"
      password: "{{ password }}"
      server_url: "{{ server }}"
      validate_certs: False
      name: "{{ activation_key_name }}"
      new_name: "{{ activation_key_name }}-{{ lifecycle_environment }}"
      organization: "{{ organization }}"
      state: 'copied'

  - name: "Set Lifecycle Environment for Activation Key"
    theforeman.foreman.activation_key:
      username: "{{ username }}"
      password: "{{ password }}"
      server_url: "{{ server }}"
      validate_certs: False
      name: "{{ activation_key_name }}-{{ lifecycle_environment }}"
      organization: "{{ organization }}"
      state: 'present'
      lifecycle_environment: "{{ lifecycle_environment }}"
