---
- hosts: localhost
  tasks:
  - name: "create lifecycle environment '{{ lifecycle_environment_name }}'"
    theforeman.foreman.lifecycle_environment:
      username: "{{ username }}"
      password: "{{ password }}"
      server_url: "{{ server }}"
      validate_certs: False
      name: "{{ lifecycle_environment_name }}"
      organization: "{{ organization }}"
      prior: "{{ prior }}"
      state: 'present'
