---
- hosts: localhost
  vars:
    organization: Sat6-CI
  tasks:
    - name: "publish '{{ content_view }}' content view"
      katello_content_view_version:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server }}"
        content_view: "{{ content_view }}"
        organization: "{{ organization }}"
        validate_certs: False
