---
- hosts: localhost
  vars:
    organization: Sat6-CI
  tasks:
    - name: "Sync repositories"
      katello_sync:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server }}"
        repository: "{{ repository }}"
        product: "{{ product }}"
        organization: "{{ organization }}"
        validate_certs: False
