---
- hosts: compose
  become: true
  become_user: compose
  tasks:
    - name: 'Clone packaging repository'
      git:
        repo: "https://{{ git_server }}/{{ git_group }}/satellite-packaging.git"
        dest: "/home/compose/satellite-packaging"
        version: "SATELLITE-{{ satellite_version }}"
        update: yes
