---
- hosts: localhost
  tasks:
    - name: "Upload file"
      katello_upload:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server }}"
        src: "{{ artifact }}"
        repository: "{{ repo }}"
        product: "{{ product }}"
        organization: "{{ organization }}"
        verify_ssl: False
