---
- hosts: localhost
  tasks:
    - name: "upload '{{ artifact | basename }}' to '{{ repo }}'"
      theforeman.foreman.content_upload:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server }}"
        src: "{{ artifact }}"
        repository: "{{ repo }}"
        product: "{{ product }}"
        organization: "{{ organization }}"
        validate_certs: False
