- job:
    name: 'sat6-unit-test-hammer-cli-foreman-virt-who-configure'
    project-type: pipeline
    build-discarder:
      days-to-keep: 21
      num-to-keep: -1
    parameters:
      - merge_request
    triggers:
      - gitlab_build_on_change
    dsl:
      !include-raw:
        - ./repos/hammer_cli_foreman_virt_who_configure.groovy
        - workflows/lib/gitlabEnv.groovy
        - workflows/test/hammer-cli.groovy
        - workflows/test/foreman-lib.groovy
        - workflows/lib/rvm.groovy
        - workflows/lib/gitlab.groovy
    notifications:
      - snapper_notifications
