- job:
    name: 'sat6-unit-test-hammer-cli-foreman-virt-who-configure'
    project-type: workflow
    logrotate:
      daysToKeep: 21
      numToKeep: -1
    parameters:
      - merge_request
    triggers:
      - gitlab_build_on_change
    dsl:
      !include-raw:
        - ./repos/hammer_cli_foreman_virt_who_configure.groovy
        - workflows/lib/gitlabEnv.groovy
        - workflows/test/hammer-cli.groovy
        - workflows/test/foreman-lib.groovy
        - workflows/lib/sendPostRequest.groovy
        - workflows/lib/messageSnapper.groovy
        - workflows/lib/rvm.groovy
        - workflows/lib/gitlab.groovy
